### ISSUE TITLE
Node.js beginner

### ISSUE THREAD

**Issue by cipry80** [cluj-javascripters/community-help#1]

**Comment by vladzelinschi** [comment]
Hello,

We really appreciate you reaching out for help to us. However, please take the time to read our issues submitting guide that you can find here - https://github.com/cluj-javascripters/community-help/blob/master/ISSUES_GUIDE.md. Unfortunately, your request is too vague and generic. Please take some time to isolate the problem and ask for more specific questions.

Thank you!
