### ISSUE TITLE
Starting out with Vue.js

### ISSUE THREAD

**Issue by alexnm** [cluj-javascripters/community-help#16]
Hello clujsers if someone played with Vue in the past couple of months, can you recommend a good way of starting to learn?

**Comment by andrei-i-gavrila** [comment]
Vue is the go to javascript framework for Laravel. There are some really nice tutorials on https://www.laracasts.com. It gives a good basic understanding from where you can start to build stuff on your own.

**Comment by deiucanta** [comment]
- Read the guide (https://vuejs.org/guide)
- For routing, use the official VueRouter (https://router.vuejs.org/en)
- For state management, use the official Vuex (https://vuex.vuejs.org/en)

Reading each of the docs above should be enough - the rest is just about figuring out best practices. Also, don't forget to use Vue CLI for scaffolding (https://github.com/vuejs/vue-cli).
