### ISSUE TITLE
select blank

### ISSUE THREAD

**Issue by mConstantDev** [cluj-javascripters/community-help#19]
![select](https://cloud.githubusercontent.com/assets/12037412/23903133/266784e4-08cc-11e7-9610-532899188f9d.png)
Hi there, i try to make a select with ng-options and for some reason in chrome appear blank select.. one mention ..in chrome inspect my values appear  here is my code :   

 <select
                                            name="project"
                                            class="form-control"
                                            ng-options="project.name for project in projects track by project.id"
                                            ng-model="projectTest"
                                            ng-init="project.id=0">
                                            <option value="project.id" selected="selected">{{project.name}}</option>
                                        </select>

 $http.get('http://ec2-52-41-170-185.us-west-2.compute.amazonaws.com:8080/projects').success(function(data){
                $scope.projects = data;    
                console.log(data);
            });

thanks

**Comment by raduGaspar** [comment]
Seems to be a CSS issue, what are the styles on that select tag?

**Comment by mConstantDev** [comment]
you`re right! thanks alot.
