### ISSUE TITLE
Node.js project

### ISSUE THREAD

**Issue by cipry80** [cluj-javascripters/community-help#3]
I try link the backend to UI. I use templating engine nunjucks.
I received the following error:  Error: template not found: home.html. 
The route is working, the template engine is setup in express.js file.
 In controller I use something like this: .
res.render('home.html', {
            title: "Nunjucks",
            data: data
        });
The code can be found here: https://github.com/cipry80/rssFeed. 
There's a lot to talk about this subject and i need a full review of my project and someone explain me why is not working or where is the problem.
Thanks.

**Comment by alexnm** [comment]
I haven't worked with this templating engine, but as far as I see, there's this express package that you can use to configure your views: https://github.com/pkolt/express-nunjucks

**Comment by cipry80** [comment]
Thanks Alex. I had fixed the problem. The issue was in express file, the path to views was not good.
