### ISSUE TITLE
webpack 2.1 and babel-loader

### ISSUE THREAD

**Issue by paulbrie** [cluj-javascripters/community-help#8]
Hi all,

do you have a working template of webpack 2.1 and babel-loader/es2015? 

Here is my current not working `webpack.config.js`:

```javascript
module.exports = {
  entry: './app/index.js',
  output: {
    filename: 'bundle.js',
    path: './public/dist'
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        use: [
          {
            loader: 'babel-loader?presets[]=es2015'
          }
        ]
      }
    ]
  }
}
```

**Comment by caisah** [comment]
Check out the new doc site https://webpack.js.org/configuration/. You'll find a lot of examples there.

**Comment by paulbrie** [comment]
Hi, Thanks a lot. It took me a lot of time to realize that wy webpack wasn't 2.1... My bad...

**Comment by vladzelinschi** [comment]
Hey,

This one is updated to Webpack 2.0 :) https://github.com/r31gN/react-redux-webpack

Let me know if it's helpful.
